import java.util.*;
public class automobiles
{
public static void main()
{
Scanner sc=new Scanner(System.in);
System.out.println("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%");
System.out.println("                     MENU                     ");
System.out.println("1.About us ");
System.out.println("2.Buy car ");
System.out.println("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%");
int car=sc.nextInt();
System.out.println();
System.out.println();
switch(car)
{
case 1:
System.out.println("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$");
System.out.println("It was founded on 13 September 1939 in modena,");
System.out.println("Italy.It was founded by Enzo Ferrari.Amsterdam,");
System.out.println("the Nitherlands.Important people in company are:");
System.out.println("Chairman - Sergio Marchionne ");
System.out.println("Vice Chairman - Piero Ferrai");
System.out.println("Ex CEO - Amedeo Felisa");
System.out.println("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$");
break;
case 2:
System.out.println("**********************************************");
System.out.println("Select any Ferrari model");
System.out.println("1.Ferrari California");
System.out.println("2.Ferrari 488");
System.out.println("3.Ferrari FF");
System.out.println("4.Ferrari 458");
System.out.println("5.Ferrari F12berlinetta");
System.out.println("**********************************************");
int selectcar=sc.nextInt();
switch (selectcar)
{
case 1:
System.out.println("**********************************************");
System.out.println("You have selected 'Ferrari California'");
System.out.println("PRIZE = 3,37,00,000/-");
System.out.println("");
System.out.println("@@@@@ ENGINE @@@@@");
System.out.println("");
System.out.println("Type - V8 3.9 liters");
System.out.println("Power - 552 hp @ 7,500 rpm(412kW)");
System.out.println("Torque - 557 lb-ft @ 4,750rpm(755 N-m)");
System.out.println("Induction - Turbocharged");
System.out.println("Bore - 86mm");
System.out.println("Stroke - 82mm");
System.out.println("Fuel type - Premium");
System.out.println("Carbon-dioxide emission - 5,000kg/years");
System.out.println("Transmission - 7-speed automatic(base)");
System.out.println("               6-speed manual");
System.out.println("");
System.out.println("");
System.out.println("##### SPEED #####");
System.out.println("");
System.out.println("Variant - Petrol");
System.out.println("Mileage (City) - 6.5 kmpl");
System.out.println("Mileage (Highway) - 10.5 kmpl");
System.out.println("");
System.out.println("");
System.out.println("***** PERFORMANCE *****");
System.out.println("");
System.out.println("Engine - 3855 cc");
System.out.println("BHP - 552.5");
System.out.println("");
System.out.println("");
System.out.println("===== SAFETY =====");
System.out.println("");
System.out.println("Cruise Control - Yes ");
System.out.println("Sun roof - no");
System.out.println("");
System.out.println("");
System.out.println("+++++ SAFETY +++++");
System.out.println("");
System.out.println("Parking Sensor - Yes");
System.out.println("Airbags - Yes");
System.out.println("**********************************************");
break;
case 2:
System.out.println("**********************************************");
System.out.println("You have selected 'Ferrari 488'");
System.out.println("PRIZE = 3,97,00,000/-");
System.out.println("");
System.out.println("@@@@@ ENGINE @@@@@");
System.out.println("");
System.out.println("Type - V8 3.9 liters");
System.out.println("Power - 661 hp @ 8,000 rpm(493kW)");
System.out.println("Torque - 561 lb-ft @ 3,000 rpm(761 N-m)");
System.out.println("Induction - Turbocharged");
System.out.println("Bore - 86mm");
System.out.println("Stroke - 83mm");
System.out.println("Fuel type - Premium");
System.out.println("Carbon-dioxide emission - 5,934kg/years");
System.out.println("Transmission - 7-speed automatic(base)");
System.out.println("");
System.out.println("");
System.out.println("##### SPEED #####");
System.out.println("");
System.out.println("Variant - Petrol");
System.out.println("Mileage (City) - 8.5 kmpl");
System.out.println("Mileage (Highway) - 12.5 kmpl");
System.out.println("");
System.out.println("");
System.out.println("***** PERFORMANCE *****");
System.out.println("");
System.out.println("Engine - 4523 cc");
System.out.println("BHP - 568.5");
System.out.println("");
System.out.println("");
System.out.println("===== SAFETY =====");
System.out.println("");
System.out.println("Cruise Control - Yes ");
System.out.println("Sun roof - yes");
System.out.println("");
System.out.println("");
System.out.println("+++++ SAFETY +++++");
System.out.println("");
System.out.println("Parking Sensor - Yes");
System.out.println("Airbags - Yes");
System.out.println("**********************************************");
break;
case 3:
System.out.println("**********************************************");
System.out.println("You have selected 'Ferrari FF'");
System.out.println("PRIZE = 4,09,00,000/-");
System.out.println("");
System.out.println("@@@@@ ENGINE @@@@@");
System.out.println("");
System.out.println("Type - V12 6.3 liters");
System.out.println("Power - 651 hp @ 8,000 rpm(485kW)");
System.out.println("Torque - 504 lb-ft @ 6,000 rpm(683 N-m)");
System.out.println("Induction - Turbocharged");
System.out.println("Bore - 94mm");
System.out.println("Stroke - 75mm");
System.out.println("Fuel type - Premium");
System.out.println("Carbon-dioxide emission - 8,160 kg/years");
System.out.println("Transmission - 7-speed automatic(base)");
System.out.println("               6-speed manual");
System.out.println("");
System.out.println("");
System.out.println("##### SPEED #####");
System.out.println("");
System.out.println("Variant - Petrol");
System.out.println("Mileage (City) - 9.5 kmpl");
System.out.println("Mileage (Highway) - 14.5 kmpl");
System.out.println("");
System.out.println("");
System.out.println("***** PERFORMANCE *****");
System.out.println("");
System.out.println("Engine - 4266 cc");
System.out.println("BHP - 634.5");
System.out.println("");
System.out.println("");
System.out.println("===== SAFETY =====");
System.out.println("");
System.out.println("Cruise Control - Yes ");
System.out.println("Sun roof - Yes");
System.out.println("");
System.out.println("");
System.out.println("+++++ SAFETY +++++");
System.out.println("");
System.out.println("Parking Sensor - Yes");
System.out.println("Airbags - Yes");
System.out.println("**********************************************");
break;
case 4:
System.out.println("**********************************************");
System.out.println("You have selected 'Ferrari 458'");
System.out.println("PRIZE = 4,16,00,000/-");
System.out.println("");
System.out.println("@@@@@ ENGINE @@@@@");
System.out.println("");
System.out.println("Type - V8 4.5  liters");
System.out.println("Power - 605 hp @ 9,000 rpm(451kW)");
System.out.println("Torque - 398 lb-ft @ 6,000 rpm(540 N-m)");
System.out.println("Induction - Atmospheric");
System.out.println("Bore - 94mm");
System.out.println("Stroke - 81mm");
System.out.println("Fuel type - Premium");
System.out.println("Carbon-dioxide emission - 5,500 kg/years");
System.out.println("Transmission - 7-speed automatic(base)");
System.out.println("");
System.out.println("");
System.out.println("##### SPEED #####");
System.out.println("Variant - Petrol");
System.out.println("Mileage (City) - 10.8 kmpl");
System.out.println("Mileage (Highway) - 14.5 kmpl");
System.out.println("");
System.out.println("");
System.out.println("***** PERFORMANCE *****");
System.out.println("");
System.out.println("Engine - 4438 cc");
System.out.println("BHP - 648.5");
System.out.println("");
System.out.println("");
System.out.println("===== SAFETY =====");
System.out.println("");
System.out.println("Cruise Control - Yes ");
System.out.println("Sun roof - Yes");
System.out.println("");
System.out.println("");
System.out.println("+++++ SAFETY +++++");
System.out.println("");
System.out.println("Parking Sensor - Yes");
System.out.println("Airbags - Yes");
System.out.println("**********************************************");
break;
case 5:
System.out.println("You have selected 'Ferrari F12berlinetta'");
System.out.println("PRIZE = 4,83,00,000/-");
System.out.println("");
System.out.println("@@@@@ ENGINE @@@@@");
System.out.println("");
System.out.println("Type - V12 6.3  liters");
System.out.println("Power - 731 hp @ 8,250 rpm(545kW)");
System.out.println("Torque - 508 lb-ft @ 6,000 rpm(689 N-m)");
System.out.println("Induction - Atmospheric");
System.out.println("Bore - 94mm");
System.out.println("Stroke - 75mm");
System.out.println("Fuel type - Premium");
System.out.println("Carbon-dioxide emission - 7,947 kg/years");
System.out.println("Transmission - 7-speed automatic(base)");
System.out.println("");
System.out.println("");
System.out.println("##### SPEED #####");
System.out.println("");
System.out.println("Variant - Petrol");
System.out.println("Mileage (City) - 15.5 kmpl");
System.out.println("Mileage (Highway) - 17.5 kmpl");
System.out.println("");
System.out.println("");
System.out.println("***** PERFORMANCE *****");
System.out.println("");
System.out.println("Engine - 4496 cc");
System.out.println("BHP - 698.5");
System.out.println("");
System.out.println("");
System.out.println("===== SAFETY =====");
System.out.println("");
System.out.println("Cruise Control - Yes ");
System.out.println("Sun roof - Yes");
System.out.println("");
System.out.println("");
System.out.println("+++++ SAFETY +++++");
System.out.println("Parking Sensor - Yes");
System.out.println("Airbags - Yes");
System.out.println("**********************************************");
break;
default:System.out.println("You have wrong choice ");
}
}
System.out.println("Do you wish to continue? (Y/N)");
String a =sc.next();
a.trim();
if (a.equalsIgnoreCase("Y"))
main();
if (a.equalsIgnoreCase("N"))
System.out.println("Thank You for Visiting");
}
}